import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, readFile, symlink, link, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createShellServer } from './shell-server'

const root = await mkdtemp(join(tmpdir(), 'slade-disk-'))
const token = 'disk-test-token-not-a-real-credential-1234567890'
const { server, stop } = await createShellServer({ root, token })
await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve))
const address = server.address()
assert(address && typeof address !== 'string')
const base = `http://127.0.0.1:${address.port}`
const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }
const request = async (path: string, body?: unknown) => fetch(`${base}/api/shell/files/${path}`, { headers, method: body ? 'POST' : 'GET', body: body ? JSON.stringify(body) : undefined })
const change = (body: unknown) => request('change', body)
const create = (path: string, content = 'initial') => change({ op: 'write', path, content, encoding: 'utf8', expectedRevision: null })
const realFetch = globalThis.fetch
try {
  assert.equal((await fetch(`${base}/api/shell/files/tree`)).status, 401)
  for (const path of ['../escape', '/absolute', 'a/../../escape', '.git/config', '.env', '.env.local', 'a\\b', 'bad\0name']) assert.equal((await create(path)).status, 400, path)
  assert.equal((await change({ op: 'write', path: 'no-precondition', content: 'bad', encoding: 'utf8' })).status, 400)
  const createdResponse = await create('src/example.txt', 'hello')
  assert.equal(createdResponse.status, 200)
  const created = await createdResponse.json()
  assert.equal(await readFile(join(root, 'src/example.txt'), 'utf8'), 'hello')
  assert.equal((await create('src/example.txt', 'overwrite')).status, 409)
  const edited = await change({ op: 'write', path: created.path, content: 'edited', encoding: 'utf8', expectedRevision: created.revision })
  assert.equal(edited.status, 200)
  assert.equal((await change({ op: 'delete', path: created.path, expectedRevision: created.revision })).status, 409)
  const editedFile = await edited.json()
  const race = await Promise.all(['one', 'two'].map((content) => change({ op: 'write', path: created.path, content, encoding: 'utf8', expectedRevision: editedFile.revision })))
  assert.deepEqual(race.map((r) => r.status).sort(), [200, 409])
  await symlink(tmpdir(), join(root, 'outside'))
  assert.equal((await create('outside/nope')).status, 400)
  await symlink(join(root, 'src/example.txt'), join(root, 'file-link'))
  assert.equal((await request('read?path=file-link')).status, 400)
  await writeFile(join(root, 'hard-target'), 'hard')
  await link(join(root, 'hard-target'), join(root, 'hard-link'))
  assert.equal((await create('hard-link')).status, 400)
  assert.equal((await create('src/example.txt/child')).status, 400)
  assert.equal((await create('oversize', 'a'.repeat(5_000_001))).status, 413)
  const binary = Buffer.from([0, 1, 2, 255])
  const binaryResponse = await change({ op: 'write', path: 'binary.bin', content: binary.toString('base64'), encoding: 'base64', expectedRevision: null })
  assert.equal(binaryResponse.status, 200)
  assert.deepEqual(await readFile(join(root, 'binary.bin')), binary)
  assert.equal((await binaryResponse.json()).encoding, 'base64')
  await mkdir(join(root, 'node_modules'))
  await writeFile(join(root, 'node_modules/hidden'), 'ignored')
  await writeFile(join(root, '.env'), 'never include this')
  const tree = await (await request('tree')).json()
  assert(tree.files.some((file: { path: string }) => file.path === created.path))
  assert(!tree.files.some((file: { path: string }) => /node_modules|\.env|outside|file-link|hard-link/.test(file.path)))
  const current = await (await request(`read?path=${created.path}`)).json()
  assert.equal((await change({ op: 'move', path: current.path, toPath: 'binary.bin', expectedRevision: current.revision })).status, 409)
  const movedResponse = await change({ op: 'move', path: current.path, toPath: 'renamed/file.txt', expectedRevision: current.revision })
  assert.equal(movedResponse.status, 200)
  assert.equal((await request(`read?path=${created.path}`)).status, 404)
  const moved = await movedResponse.json()
  assert.equal((await change({ op: 'delete', path: moved.path, expectedRevision: moved.revision })).status, 200)

  // Real frontend storage client against the real HTTP backend, not a mocked API.
  const storage = new Map<string, string>()
  Object.assign(globalThis, { localStorage: { getItem: (k: string) => storage.get(k) ?? null, setItem: (k: string, v: string) => storage.set(k, v), removeItem: (k: string) => storage.delete(k) } })
  const disk = await import('../src/store/diskFs')
  const { useShell } = await import('../src/lib/shell')
  const { useFs } = await import('../src/store/fs')
  const { applyAgentOutputWithGit } = await import('../src/engine/agent')
  globalThis.fetch = (input, init) => realFetch(typeof input === 'string' && input.startsWith('/') ? base + input : input, init)
  useFs.getState().writeFile('legacy.txt', 'browser-only')
  const browserBefore = JSON.stringify(useFs.getState().listAllFiles())
  useShell.getState().connect(token, root)
  await disk.refreshDiskTree()
  assert.equal(await disk.maybeReadDiskFile('legacy.txt'), null, 'Connecting must not auto-import browser files')
  const imported = await disk.writeDiskFile('legacy.txt', 'browser-only', 'utf8', null)
  assert.equal(await readFile(join(root, 'legacy.txt'), 'utf8'), 'browser-only')
  const reviewBefore = await disk.reviewDiskImport([
    useFs.getState().readFile('legacy.txt')!,
    { ...useFs.getState().readFile('legacy.txt')!, path: 'new-import.txt' },
    { ...useFs.getState().readFile('legacy.txt')!, path: '.env' },
  ])
  assert(reviewBefore[0]!.identical && !reviewBefore[0]!.selected)
  assert(reviewBefore[1]!.selected && !reviewBefore[1]!.disk)
  assert(reviewBefore[2]!.result && !reviewBefore[2]!.selected)
  await writeFile(join(root, 'legacy.txt'), 'external editor update')
  const reviewConflict = await disk.reviewDiskImport([useFs.getState().readFile('legacy.txt')!])
  assert(!reviewConflict[0]!.selected && reviewConflict[0]!.disk && !reviewConflict[0]!.identical, 'Conflicts start unchecked')
  await assert.rejects(disk.writeDiskFile('legacy.txt', 'stale import', 'utf8', imported.revision), /changed on disk/)
  const session = disk.workspaceSession()
  const context = await disk.diskWorkspaceContext('legacy.txt', session)
  assert(context.includes('external editor update'))
  await applyAgentOutputWithGit('```text:new-agent.txt\nwritten by model\n```', { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' }, workspaceSession: session })
  assert.equal(await readFile(join(root, 'new-agent.txt'), 'utf8'), 'written by model')
  const appended = '```fs:append:new-agent.txt\n + appended once\n```'
  const { extractFsActions } = await import('../src/lib/fs')
  await applyAgentOutputWithGit(appended, { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' }, workspaceSession: session })
  await applyAgentOutputWithGit(appended, { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' }, workspaceSession: session, alreadyApplied: new Set(extractFsActions(appended).map((action) => JSON.stringify(action))) })
  assert.equal(await readFile(join(root, 'new-agent.txt'), 'utf8'), 'written by model + appended once', 'Synthesis must not replay worker append operations')
  const aborted = new AbortController(); aborted.abort()
  await assert.rejects(applyAgentOutputWithGit('```text:cancelled-write.txt\nno\n```', { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' }, workspaceSession: session, signal: aborted.signal }))
  assert.equal(await disk.maybeReadDiskFile('cancelled-write.txt'), null)
  const bashResponse = await realFetch(`${base}/api/shell/execute`, { method: 'POST', headers, body: JSON.stringify({ command: 'cat new-agent.txt; printf shell-change > from-bash.txt' }) })
  assert((await bashResponse.text()).includes('written by model'), 'bash sees generated file edits')
  await disk.refreshDiskTree()
  assert.equal((await disk.readDiskFile('from-bash.txt')).content, 'shell-change', 'Files sees bash edits')
  await writeFile(join(root, 'legacy.txt'), 'newer external edit')
  await disk.readDiskFile('legacy.txt') // A UI read must not erase the model's old revision.
  await assert.rejects(applyAgentOutputWithGit('```text:legacy.txt\nstale model change\n```', { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' }, workspaceSession: session }), /changed on disk/)
  assert.equal(await readFile(join(root, 'legacy.txt'), 'utf8'), 'newer external edit')
  assert.equal(JSON.stringify(useFs.getState().listAllFiles()), browserBefore, 'Disk edits/imports preserve browser originals')
  const disconnectedSession = disk.workspaceSession()
  useShell.getState().disconnect()
  assert.deepEqual(disk.useDiskFs.getState().entries, [])
  await assert.rejects(applyAgentOutputWithGit('```text:never-fallback.txt\nno\n```', { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' }, workspaceSession: disconnectedSession }), /connection changed/)
  assert.equal(useFs.getState().readFile('never-fallback.txt'), undefined)
  assert.equal(useFs.getState().readFile('legacy.txt')?.content, 'browser-only')
  await applyAgentOutputWithGit('```text:offline.txt\noffline\n```', { source: { origin: 'model', modelId: 'test', modelLabel: 'Test' } })
  assert.equal(useFs.getState().readFile('offline.txt')?.content, 'offline')
  console.log('Disk filesystem integration tests passed: authentication, path protections, CRUD, revision conflicts, concurrent writes, binary files, limits, browser preservation, explicit import, agent routing, bash parity, stale context protection and offline fallback.')
} finally {
  globalThis.fetch = realFetch
  stop(); server.closeAllConnections()
  await rm(root, { recursive: true, force: true })
}
