/**
 * Slade core domain types.
 *
 * Everything the app exchanges is modeled here with discriminated unions so
 * the compiler can prove exhaustive handling of provider events, failure
 * classes and artifact kinds.
 */

/* ------------------------------------------------------------------ */
/* Providers & models                                                  */
/* ------------------------------------------------------------------ */

export type ProviderId = 'mock' | 'openai' | 'anthropic' | 'google' | 'openrouter' | 'openai-compatible'

export type FailureClass =
  | 'success'
  | 'soft_rate_limit'
  | 'hard_quota'
  | 'auth'
  | 'timeout'
  | 'network'
  | 'overloaded'
  | 'aborted'
  /** The provider understood the request and refused it (HTTP 400 and friends). */
  | 'bad_request'
  /**
   * The provider answered, but the output budget ran out before any *answer*
   * text arrived — typically a reasoning model that spent every token
   * thinking. Not a sick model: a too-small `max_tokens`. Waiting cannot fix
   * it (so no cooldown); raising the budget can, and the engine does exactly
   * that once before walking the chain.
   */
  | 'token_budget'
  | 'unknown'

/** What a mock model should do on its next request (failover demo control). */
export type MockSimulate = 'ok' | 'soft_rate_limit' | 'hard_quota' | 'timeout' | 'network' | 'auth' | 'bad_request'

export interface ModelOverrides {
  temperature?: number
  maxTokens?: number
  systemPrompt?: string
  /** Whether to show thinking / reasoning generated by this model. */
  showThoughts?: boolean
}

export interface ModelDef {
  id: string
  /** Human label shown in the UI, e.g. "Claude Sonnet 4.5". */
  label: string
  /**
   * Id of the provider *instance* (in `settings.providers`) this model runs
   * on. The factory instances keep their kind as id — `'openai'`, `'mock'`… —
   * so settings saved before providers became user-managed keep resolving.
   */
  provider: string
  /** Model identifier passed to the provider API. */
  apiModel: string
  /** Base URL override (openai-compatible endpoints: Groq, OpenRouter, Ollama…). */
  baseURL?: string
  enabled: boolean
  /** Whether to show thinking / reasoning generated by this model. */
  showThoughts?: boolean
  /** USD per 1k tokens, used for cheapest-first routing and display. */
  costPer1kIn?: number
  costPer1kOut?: number
  contextWindow?: number
  overrides?: ModelOverrides
  /** Only meaningful for mock models. */
  simulate?: MockSimulate
}

export const FAILURE_LABEL: Record<FailureClass, string> = {
  success: 'Success',
  soft_rate_limit: 'Rate limited',
  hard_quota: 'Quota exhausted',
  auth: 'Auth failure',
  timeout: 'Timed out',
  network: 'Network error',
  overloaded: 'Provider overloaded',
  aborted: 'Cancelled',
  bad_request: 'Request rejected',
  token_budget: 'Token budget',
  unknown: 'Unknown error',
}

/* ------------------------------------------------------------------ */
/* Provider stream events                                              */
/* ------------------------------------------------------------------ */

export type StreamEvent =
  | { type: 'delta'; text: string }
  /**
   * Internal reasoning ("thinking") text. It is provenance for the answer,
   * never the answer itself — the engine uses it as liveness (a model that is
   * still thinking has not stalled) and as evidence when a turn comes back
   * with no content at all.
   */
  | { type: 'reasoning'; text: string }
  | { type: 'usage'; promptTokens?: number; completionTokens?: number; reasoningTokens?: number }
  /**
   * `finishReason` is the provider's own stop reason; `truncated` is true when
   * that reason was the token cap rather than the model finishing its answer.
   */
  | { type: 'done'; finishReason?: string; truncated?: boolean }
  | { type: 'error'; failure: FailureClass; message: string; retryable: boolean }

export interface ChatTurn {
  role: 'user' | 'assistant'
  text: string
  /** Images inlined for vision models; other files folded into text. */
  images?: { mime: string; dataURL: string; name: string }[]
  textFiles?: { name: string; content: string }[]
  binaryNotes?: string[]
}

/* ------------------------------------------------------------------ */
/* Artifacts                                                           */
/* ------------------------------------------------------------------ */

/** Every GitHub call Slade can surface as an in-chat activity card. */
export type GitHubActionKind =
  | 'get-file'
  | 'create-file'
  | 'update-file'
  | 'delete-file'
  | 'get-blob'
  | 'create-blob'
  | 'get-tree'
  | 'create-tree'
  | 'create-branch'
  | 'delete-branch'
  | 'get-branch'
  | 'list-branches'
  | 'update-ref'
  | 'get-commit'
  | 'create-commit'
  | 'create-pr'
  | 'merge-pr'
  | 'get-pr'
  | 'list-prs'
  | 'create-issue'
  | 'list-issues'
  | 'create-gist'
  | 'list-gists'
  | 'search-code'
  | 'search-repos'
  | 'list-repos'
  | 'get-repo'
  | 'clone-repo'
  | 'test-token'
  | 'rate-limit'
  | 'sign-in'
  | 'sign-out'
  | 'other'

export interface GitHubActionInfo {
  kind: GitHubActionKind
  /** Card title, already prefixed. */
  title: string
  /** The path, branch, query, or repo the call touched. */
  subject: string
  repo?: string
  ref?: string
}

export type GitHubActionStatus = 'running' | 'done' | 'error' | 'cancelled'

/** Persistable, read-only content for one GitHub action card. */
export interface GitHubActionArtifact extends GitHubActionInfo {
  id: string
  status: GitHubActionStatus
  at: number
  elapsedMs?: number
  error?: string
  /** How many identical calls this card stands for. */
  count: number
}

export type ArtifactKind =
  | 'image'
  | 'code'
  | 'doc'
  | 'sheet'
  | 'audio'
  | 'video'
  | 'archive'
  | 'unknown'

export type ArtifactSource = { origin: 'user' } | { origin: 'model'; modelId: string; modelLabel: string }

/** Where a file came from when it was not uploaded from disk (GitHub repos). */
export interface RemoteSource {
  kind: 'github'
  /** `owner/name`. */
  repo: string
  /** Branch, tag or commit sha the file was read at. */
  ref: string
  path: string
  /** Canonical permalink on github.com. */
  url: string
  sha?: string
}

export interface Artifact {
  id: string
  name: string
  mime: string
  size: number
  kind: ArtifactKind
  createdAt: number
  provenance: ArtifactSource
  /** Set when the artifact was pulled from a repository rather than uploaded. */
  remote?: RemoteSource
  /** Set when the artifact is backed by a file in the local file system. */
  localPath?: string
  /** Small artifacts are persisted as data URLs; larger ones live in memory. */
  dataURL?: string
  /** Runtime object URL (never persisted; recreated from dataURL on load). */
  blobUrl?: string
  /** Text preview for code / docs / sheets. */
  text?: string
  /** Parsed CSV columns/rows for sheet preview. */
  columns?: string[]
  rows?: string[][]
  /** Media duration in seconds when known. */
  durationSec?: number
  /** True when the artifact exists only for this session (large files). */
  ephemeral?: boolean
}

/* ------------------------------------------------------------------ */
/* Local file system                                                   */
/* ------------------------------------------------------------------ */

export type FsFileEncoding = 'utf8' | 'base64'

/**
 * One file stored in Slade's local file system. Shared across the
 * orchestrator, worker steps, and chat turns so agents can create, inspect,
 * update, and organize persistent files in a workspace.
 */
export interface FsFile {
  /** Canonical normalized relative path, e.g. "src/app.ts" or "data/sales.csv". */
  path: string
  /** Basename of the file, e.g. "app.ts". */
  name: string
  /** File content (UTF-8 string, or base64 payload when `encoding === 'base64'`). */
  content: string
  encoding?: FsFileEncoding
  mime: string
  kind: ArtifactKind
  size: number
  createdAt: number
  updatedAt: number
  createdBy: ArtifactSource
  updatedBy: ArtifactSource
  /** Incremented every time the file is written/updated (starts at 1). */
  version: number
  /** Conversation id that last modified this file, when written during a turn. */
  conversationId?: string
  /** Message or step id that last modified this file. */
  messageId?: string
  /** Upstream GitHub repository source when pulled from or pushed to GitHub. */
  remote?: RemoteSource
  /** True when the file was modified locally since it was last pulled/pushed to `remote`. */
  dirty?: boolean
}

export type FsOpKind = 'create' | 'update' | 'delete' | 'move' | 'pull'

/** Record of one file system operation performed by an agent or model. */
export interface FsOpRecord {
  op: FsOpKind
  path: string
  fromPath?: string
  size?: number
  version?: number
  at: number
}

/* ------------------------------------------------------------------ */
/* Orchestrator agent (agent mode)                                     */
/* ------------------------------------------------------------------ */

export type AgentPhase =
  | 'planning'
  | 'executing'
  | 'synthesizing'
  | 'complete'
  | 'error'
  /**
   * The orchestrator stopped before delegating to ask the user something. The
   * turn is finished (nothing is in flight) and the run resumes in place as
   * soon as the last question has been answered.
   */
  | 'awaiting_input'

export type AgentStepStatus = 'pending' | 'running' | 'complete' | 'error' | 'skipped'

/* ------------------------------------------------------------------ */
/* Clarification questions (agent asks, user chooses)                  */
/* ------------------------------------------------------------------ */

/** One selectable choice in a question the agent asked. */
export interface AgentQuestionOption {
  id: string
  label: string
  /** Optional one-line explanation of what picking this option means. */
  hint?: string
}

/** What the user chose. Stored so the answer survives any later re-render. */
export interface AgentQuestionAnswer {
  /** Ids of the predefined options that were picked (empty for a typed answer). */
  optionIds: string[]
  /** Labels resolved at answer time, so the record outlives the option list. */
  labels: string[]
  /** The free-text answer, when the user typed their own instead of choosing. */
  custom?: string
  /** Canonical one-line answer, exactly as it is handed back to the model. */
  text: string
}

export type AgentQuestionStatus = 'pending' | 'answered' | 'skipped'

/**
 * One multi-choice question the orchestrator asked before it could plan.
 * Questions are answered one at a time: an answered question collapses into a
 * read-only answer card and the next pending one is revealed underneath it.
 */
export interface AgentQuestion {
  id: string
  /** The question itself. */
  prompt: string
  /** Optional context: why the agent needs to know. */
  detail?: string
  options: AgentQuestionOption[]
  /**
   * Whether the user may type their own answer instead of picking an option.
   * Almost always true — a choice list that cannot be contradicted is a trap.
   */
  allowCustom: boolean
  /**
   * Hint for the free-text field, used both under the "type your own answer"
   * option and as the field's placeholder, e.g. `e.g. "Q2 vs Q2 last year"`.
   */
  customLabel?: string
  /** True when more than one option may be selected. */
  multiple?: boolean
  status: AgentQuestionStatus
  answer?: AgentQuestionAnswer
  /** Why the question was skipped, when it wasn't the user's own choice. */
  note?: string
  askedAt: number
  answeredAt?: number
  /** Model that asked, for attribution on the card. */
  modelId?: string
}

/** One card in the agent's chronological output: a thought segment or GitHub call. */
export type AgentTimelineItem =
  | {
      id: string
      type: 'thought'
      /** Planning, synthesis, or the id of the worker step that produced it. */
      sourceId: string
      modelId: string
      text: string
      /** True only while this contiguous thought segment is being streamed. */
      streaming?: boolean
    }
  | {
      id: string
      type: 'github'
      card: GitHubActionArtifact
    }

/**
 * One subtask the orchestrator delegated to a worker model. Persisted with
 * the message so the whole run stays inspectable after a reload.
 */
export interface AgentStep {
  id: string
  title: string
  /** Full self-contained prompt the worker received. */
  prompt: string
  modelId: string
  /** Resolved at plan time; kept separately so a renamed model still renders. */
  modelLabel: string
  status: AgentStepStatus
  /** The worker's full output. */
  result?: string
  /** Internal thinking / reasoning text generated by the worker model. */
  reasoning?: string
  error?: string
  /** Failures inside this step's own failover walk, tried order. */
  attempts: AttemptFailure[]
  /** Worker model ids that failed before this step produced output. */
  failedChain: string[]
  elapsedMs?: number
  /** True when the worker's output was cut off by the token cap. */
  truncated?: boolean
  /** Files created, updated, moved, or deleted in the local file system by this step. */
  fsOps?: FsOpRecord[]
}

export interface AgentRun {
  phase: AgentPhase
  /** The user's goal this run is executing. */
  goal: string
  orchestratorModelId: string
  steps: AgentStep[]
  /** Orchestrator's internal thinking / reasoning during planning. */
  planningReasoning?: string
  /** Orchestrator's one-line strategy note from the planning call. */
  strategy?: string
  /** Set when planning had to fall back (unparseable plan → single step). */
  note?: string
  error?: string
  startedAt: number
  finishedAt?: number
  /** Aggregate local file system operations performed across this run. */
  fsOps?: FsOpRecord[]
  /**
   * Thought and GitHub cards in the exact order they were emitted. Thought
   * segments split around GitHub calls, so a live call appears between the
   * thought card that was open and the next thought card.
   */
  timeline?: AgentTimelineItem[]
  /**
   * Identifies the GitHub cards this run produced, so they render inside the
   * run's answer rather than in the chat panel.
   */
  githubScope?: string
  /**
   * Clarification questions the orchestrator asked, in the order they were
   * asked. Answered ones keep their chosen answer, so the whole exchange stays
   * inspectable after the run continues (and after a reload).
   */
  questions?: AgentQuestion[]
  /** How many ask-rounds this run has already used (capped, see `lib/questions`). */
  questionRounds?: number
  /**
   * Where the project's roadmap / milestone file stands after this run:
   * previous, current and next step plus overall progress. Present only when
   * a roadmap was actually used (see `src/lib/roadmap.ts`).
   */
  roadmap?: RoadmapReport
}

/* ------------------------------------------------------------------ */
/* Roadmap tracking (orchestrator completion report)                   */
/* ------------------------------------------------------------------ */

export type RoadmapStatus = 'done' | 'active' | 'todo'

/** One roadmap step as it appears on the completion timeline. */
export interface RoadmapTimelineStep {
  /** 1-based position among all of the roadmap's steps. */
  index: number
  label: string
  status: RoadmapStatus
  /** Enclosing milestone / section heading, when the roadmap has one. */
  group?: string
  /** True when this step's status changed during the run. */
  changed?: boolean
}

/** A step whose status moved during the run (or that was added / removed). */
export interface RoadmapChange {
  label: string
  from: RoadmapStatus | 'new'
  to: RoadmapStatus | 'removed'
}

export interface RoadmapProgress {
  done: number
  active: number
  total: number
  /** Whole-number completion, `round(done / total * 100)`. */
  percent: number
}

/**
 * The completion timeline Slade shows under an orchestrated run's final
 * answer. Derived by diffing the roadmap file before and after the run — never
 * from a model's own claim about it — and persisted with the message.
 */
export interface RoadmapReport {
  /** Local file system path of the roadmap that was used, e.g. `ROADMAP.md`. */
  path: string
  title?: string
  previous?: RoadmapTimelineStep
  current?: RoadmapTimelineStep
  next?: RoadmapTimelineStep
  /** Overall completion after the run. */
  progress: RoadmapProgress
  /** Completion when the run started; absent when the roadmap was created by the run. */
  before?: RoadmapProgress
  /** Status transitions this run made to the roadmap, in roadmap order. */
  changes: RoadmapChange[]
}

/* ------------------------------------------------------------------ */
/* Messages & conversations                                            */
/* ------------------------------------------------------------------ */

export type Role = 'user' | 'assistant'
export type MessageStatus = 'pending' | 'streaming' | 'complete' | 'error' | 'cancelled'

/**
 * One model that was tried for a turn, and what the provider actually said.
 * Persisted with the message so a failed turn can explain itself later.
 */
export interface AttemptFailure {
  modelId: string
  label: string
  failure: FailureClass
  /** Provider-supplied reason, already redacted and humanized. */
  message: string
  /** HTTP status when the failure came from a response, else 0. */
  status?: number
  /** Wall-clock ms spent on this attempt before it failed. */
  elapsedMs: number
  /** True when the model failed after it had already started streaming. */
  midStream: boolean
}

/** A mid-stream handoff from one model to another. */
export interface Handoff {
  fromModelId: string
  fromModelLabel: string
  toModelId: string
  /** Character offset in the final message content where the handoff happened. */
  atChar: number
  at: number
}

export interface Usage {
  promptTokens?: number
  completionTokens?: number
  /**
   * Tokens billed for internal reasoning. Always a subset of
   * `completionTokens` — when the two are close and the answer is empty, the
   * budget was consumed by thinking rather than by output.
   */
  reasoningTokens?: number
}

export interface Message {
  id: string
  role: Role
  conversationId: string
  content: string
  /** Internal thinking / reasoning text emitted by the model during generation. */
  reasoning?: string
  createdAt: number
  status: MessageStatus
  /** Model that produced (or last contributed to) this message. */
  modelId?: string
  /** Ordered chain of models that contributed output, primary first. */
  chain?: string[]
  /** Models that failed before any output started, in tried order. */
  failedChain?: string[]
  /** Mid-stream handoffs. */
  handoffs?: Handoff[]
  attachmentIds?: string[]
  usage?: Usage
  error?: string
  errorClass?: FailureClass
  /** Per-model detail for every attempt that failed during this turn. */
  attempts?: AttemptFailure[]
  editedAt?: number
  /** Latency to first token, ms. */
  ttftMs?: number
  /** True when the answer stopped at the output token cap instead of finishing. */
  truncated?: boolean
  /** Present when this reply was produced by the orchestrator agent. */
  agent?: AgentRun
}

export interface Conversation {
  id: string
  title: string
  createdAt: number
  updatedAt: number
  messages: Message[]
  /** Per-conversation primary model override. */
  modelId?: string
  /** When true, sends go through the orchestrator agent instead of the plain chain. */
  agentEnabled?: boolean
  /**
   * Archived conversations are kept (and stay searchable) but leave the main
   * sidebar list for the collapsible "Archived" group. Absent means active.
   * Archiving never touches `updatedAt`: it is not chat activity.
   */
  archived?: boolean
}

/* ------------------------------------------------------------------ */
/* Health                                                              */
/* ------------------------------------------------------------------ */

export type HealthState = 'available' | 'cooldown' | 'disabled' | 'error'

export interface ModelHealth {
  modelId: string
  state: HealthState
  cooldownUntil?: number
  consecutiveFailures: number
  lastError?: { at: number; failure: FailureClass; message: string }
  /** Exponential moving average of full-request latency, ms. */
  avgLatencyMs?: number
  totalRequests: number
  totalFailures: number
  totalTokensIn: number
  totalTokensOut: number
}

export interface TokenHealth {
  tokenId: string
  state: HealthState
  cooldownUntil?: number
  consecutiveFailures: number
  lastError?: { at: number; failure: FailureClass; message: string }
  totalRequests: number
  totalFailures: number
}

/* ------------------------------------------------------------------ */
/* Settings                                                            */
/* ------------------------------------------------------------------ */

export type FailoverStrategy = 'priority' | 'fastest' | 'cheapest'
export type ThemePref = 'light' | 'dark' | 'system'
export type Density = 'compact' | 'cozy' | 'roomy'

export interface DefaultsSettings {
  temperature: number
  topP: number
  maxTokens: number
  systemPrompt: string
  stream: boolean
  typingIndicator: boolean
  /** Whether to show model thinking / reasoning by default. */
  showThoughts?: boolean
  autoScroll: 'smooth' | 'instant' | 'off'
  failoverStrategy: FailoverStrategy
  /** Max gap between streamed chunks before the stream is declared stalled. */
  requestTimeoutMs: number
  /** How long to wait for the *first* token. Reasoning models need more. */
  firstTokenTimeoutMs: number
}

export interface ArtifactSettings {
  collapsedByDefault: boolean
  autoExpandImages: boolean
  maxPreviewHeight: number
}

/** Orchestrator agent configuration (Settings → Agent). */
export interface AgentSettings {
  /** Model that plans, delegates and synthesizes. Undefined = top of the chain. */
  orchestratorModelId?: string
  /** Upper bound on subtasks per run. */
  maxSteps: number
  /** How many workers may run at once (1 = strictly sequential). */
  maxParallel: number
  /** When false the plan card collapses worker outputs to one line each. */
  expandStepResults: boolean
  /**
   * Output token ceiling for the orchestrator's own calls (plan, each worker
   * step, synthesis). Deliberately well above the chat default: a step is a
   * whole deliverable ("build the app"), and reasoning models bill their
   * thinking against the same cap — a 4k ceiling is how a step comes back
   * empty. Raising a ceiling costs nothing unless the tokens are used.
   */
  stepMaxTokens: number
  /**
   * When true, agents automatically read existing files from the local file
   * system as workspace context and store emitted files back into it.
   */
  useLocalFs: boolean
}

export interface AppearanceSettings {
  theme: ThemePref
  fontSize: number
  density: Density
  codeTheme: 'auto' | 'light' | 'dark'
  reduceMotion: boolean
  enterToSend: boolean
}

/**
 * An individual API token/key configured under a provider connection.
 * Multiple tokens can be pooled for automatic load balancing and failover
 * when rate limits (429) or quota errors (402) occur.
 */
export interface ApiTokenDef {
  /** Unique token identifier. */
  id: string
  /** The secret API key string. */
  key: string
  /** Optional human label, e.g. "Primary", "Personal Tier", "Backup". */
  label?: string
  /** Whether this token is active in the candidate pool (default true). */
  enabled?: boolean
  /** Timestamp when added. */
  createdAt?: number
}

/**
 * One configured provider connection. Slade ships with one instance per
 * supported kind, and more can be added (Settings → Providers) — several
 * OpenAI-compatible endpoints (Groq, DeepSeek, Ollama…) or a second account
 * on the same provider each get their own entry, key and models.
 */
export interface ProviderDef {
  /** Unique instance id. Factory instances reuse their kind as id. */
  id: string
  /** Which wire protocol/adapter this connection speaks. */
  kind: ProviderId
  /** Display name, e.g. "OpenAI" or "Groq". Editable. */
  label: string
  /** Primary / default API key (kept in sync with apiKeys[0]). */
  apiKey: string
  /** Pool of API tokens for rotation and independent cooldown tracking. */
  apiKeys?: ApiTokenDef[]
  /** Default endpoint override for kinds that support it (openai-compatible). */
  baseURL?: string
}

export interface Settings {
  version: 1
  models: ModelDef[]
  defaults: DefaultsSettings
  artifacts: ArtifactSettings
  appearance: AppearanceSettings
  agent: AgentSettings
  providers: ProviderDef[]
  pinnedModelId?: string
}

/* ------------------------------------------------------------------ */
/* Toasts & misc UI                                                    */
/* ------------------------------------------------------------------ */

export type ToastKind = 'info' | 'success' | 'warn' | 'error'

export interface Toast {
  id: string
  kind: ToastKind
  title: string
  detail?: string
  /** One inline button, e.g. "Undo". Clicking it runs `onClick` and dismisses the toast. */
  action?: { label: string; onClick: () => void }
}
